query getVariant($id: ID!, $options: [SelectedOptionInput!]!) {
  node(id: $id) {
    ... on Product {
      variantBySelectedOptions(selectedOptions: $options) {
        title
        priceV2 {
          amount
          currencyCode
        }
        product {
          id
          title
        }
      }
    }
  }
}
