query getAllProducts {
  products(first: 2) {
    edges {
      node {
        id
        handle
        title
        images(first: 1) {
          edges {
            node {
              id
              originalSrc
            }
          }
        }
        options {
          id
          name
          values
        }
      }
    }
  }
}
